# -*- coding: utf-8 -*-
"""ompy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WD7jxGUHmtn9xW2tgJpAbPxxps9FZ8Cl
"""

import math
import re

def to_dec_degrees(
    theta, 
    from_radians=True, 
    from_degs_mins_secs=False, 
    from_gradians=False, 
    from_turns=False):
  
    arguments = list(locals().values())[-3:]
    
    if any(arguments):

        try:
            assert arguments.count(True) == 1

        except AssertionError:
            raise TypeError(
                "Unit error; more than one unit requested for converting.\nOnly one supported.")
    

    if from_degs_mins_secs:

        try:
            assert type(theta) == str and re.fullmatch("[0-9]+[d"+str(chr(176))+"][0-9]{2}'[0-9]{2}''", theta)

        except AssertionError:
            raise TypeError(
                "Angle ", theta, 
                " class type not supported; not matching correct format.",
                "Requested numeric type and degrees, minutes, seconds pattern(D", 
                str(chr(176)), "MM'SS'') or (DdMM'SS''")
            
        if str(chr(176)) in theta:
            separator = str(chr(176))

        else:
            separator = "d"

        degs_mins_secs = theta.split(separator)
        degrees = float(degs_mins_secs[0])
        minutes = float(degs_mins_secs[1].split("'")[0])
        seconds = float(degs_mins_secs[1].split("'")[1])
        return round(degrees + (minutes/60) + (seconds/3600), 15)

